### PR TITLE
feat: add shadow branch for tracer

### PR DESCRIPTION
**Pull request by huaixv**
This commit creates a shadow branch for ysyx-tracer.
So the tracer commit will not apper in our work branch anymore.

Adapted from this SO answer: https://stackoverflow.com/a/15993574

TODO: it will make all changes staged, maybe there is some method to get rid of this side effect?

### CODE REVIEW

**Comment by retrhelo** [comment]
This approach seems to lead to change loss. It can be easily invoked by:

1. Make some changes on `master` branch, but don't stage or commit them.
image

2. Use `make` to build the project, say, for testing purpose. Notice that the change is staged.
image


3. Use `git checkout ysyx-tracer` to switch to `ysyx-tracer` branch, to checkout if tracer works properly.
4. Use `git checkout master` to switch to orignal branch.
image


The changes made on `master` branch just disappears. The reason behind this is not clear. However, in working situations, such a bug can cause great loss.

The idea of shadow branch for tracing is impressive, but this bug must be solved first before current PR gets accepted.

**Comment by huaixv** [comment]
This is just how `git checkout` works, it will update the staging area and working tree to match the commit(branch) specified.
But there is no data loss, as all changes have been commited to the tracer branch already.
That's why the script use `git checkout --detach`, `git reset --soft`, `git checkout` to keep the working tree untouched.

**Comment by huaixv** [comment]
Some IDEs (such as JB's products) will give a warning when you checkout another branch if working tree is not clean.
They have a `Smart Checkout` feature for this, which stash all changes, do real checkout, and then unstash.

**Comment by retrhelo** [comment]
> But there is no data loss, as all changes have been commited to the tracer branch already.

Indeed. However, after switching back to `master`, I can no longer find the changes made previously. Restoring them from `ysyx-tracer` branch would require extra commands, which brings complexity. **Not all students in YSYX project are experts in Git**. I think we should not bring them unnecessary problems like this. Besides, these changes may be buggy, hence not ready for a commit.

Considering that this situation is easy to invoke, I'd prefer that the changes made on `master` stay untouched when I switch back from `ysyx-tracer`, or at least there be a warning before switching to `ysyx-tracer`.

> They have a Smart Checkout feature for this, which stash all changes, do real checkout, and then unstash.

Talking about _stash_, I wonder if `git stash` would help to solve this problem?

**Comment by huaixv** [comment]
> However, after switching back to `master`, I can no longer find the changes made previously. Restoring them from `ysyx-tracer` branch would require extra commands, which brings complexity. **Not all students in YSYX project are experts in Git**. I think we should not bring them unnecessary problems like this.

In my opinion, the `ysyx-tracer` branch is only for orginality check and is likely used only by the TAs. And daily development should be done on `master` branch, which will not cause problems.

> Besides, these changes may be buggy, hence not ready for a commit.

The tracer code currently used also creates buggy commits, we mostly can't assure that all code compiles or behaves as expected when we issue a `make` command.

> or at least there be a warning before switching to `ysyx-tracer`.

Maybe we can add a warning message in the handouts.

> Talking about _stash_, I wonder if `git stash` would help to solve this problem?

Stash is good for this purpose, as it can preserve working tree, staging area.
The problem is that we have to do `git stash` and `git stash apply` to trace untracked files.
`git stash store $(git stash stash create)` doesn't accept a `--include-untracked` option like `git stash`.

Also it will not create a empty stash (like `git commit --allow-empty`) when the work tree is clean, which makes it a bit tricky if we want to do unstash after switching back to `master`.

**Comment by retrhelo** [comment]
> And daily development should be done on `master` branch, which will not cause problems.

> Maybe we can add a warning message in the handouts.

We just can't make such an assumption. Hiding the risk will not prevent students from invoking it. And I don't think adding warnings into handouts helps. Working with multiple branches are common and basic, we can't stick the students to `master` branch only.

> The tracer code currently used also creates buggy commits, we mostly can't assure that all code compiles or behaves as expected when we issue a make command.

This patch is to solve the problem that the original tracer creates unwanted commits (I'd refer to them as "trush commits") on current branch. It turns meaningless if the new tracer creates unwanted commits as the old does. Not to mention it also introduce complexity and "risks".

> In my opinion, the ysyx-tracer branch is only for orginality check

I agree with it. Contents in `ysyx-tracer` doesn't matter, what really matters are commits and their timeline. Thus, I think we can create empty commits on `ysyx-tracer`. And use `git stash` before/after switch into/from `ysyx-tracer`. As the script doesn't `git add` any files, untracked files stay untouched, too.

```bash
git stash
git checkout ysyx-tracer
### Make an empty commit on ysyx-tracer branch ###
git checkout master
git stash pop
```

**Comment by huaixv** [comment]
Okay, we can just add `git reset` at the end of script to unstage all changes, so checking out another branch will not overwrite these changes (Git will raise an error on this).

> Contents in `ysyx-tracer` doesn't matter

I disagree. It's important to keep track of how your code base grows in the tracer branch through the YSYX project, and that's essential for originality, not a bunch of empty commits with only msgs, `uptime` or `uname`.
And I think this is why the current code also has `git add ..` line.

> This patch is to solve the problem that the original tracer creates unwanted commits on current branch.

I don't think these commits are unwanted or trash, they should just go to the right branch and never get in my way if I want to browse git logs.

> Hiding the risk will not prevent students from invoking it.

> **Not all students in YSYX project are experts in Git**.

> And I don't think adding warnings into handouts helps.

Students should RTFM or STFW and get to know what happens under the hood when they make a Git (or whatever) operation.
And I will appreciate it if this could be emphasized in the YSYX/PA handouts.

**Comment by retrhelo** [comment]
> It's important to keep track of how your code base grows in the tracer branch through the YSYX project

Commits on `master` branch are for this purpose.

> I don't think these commits are unwanted or trash, they should just go to the right branch and never get in my way if I want to browse git logs.

We'll check out commits on `ysyx-tracer` to make sure that the work is done individually. However, as commits generated by script provide only fixed information (like user, timestamp, _etc_.), they provide no useful information for project management. From this aspect, I think they are "unwanted". I agree with you that these commits "should just go to the right branch", like `ysyx-tracer`.

> Students should RTFM or STFW and get to know what happens under the hood when they make a Git (or whatever) operation.

If both branches are maintained by students themselves, then it sounds reasonable. However, since `ysyx-tracer` is instead maintained by a script provided by the project, I'd say it's kind of lacking responsibility. **It's not reasonable for students to take "risks" introduced by the project.**

> we can just add git reset at the end of script to unstage all changes, so checking out another branch will not overwrite these changes (Git will raise an error on this).

In this case, why not make some modifications to your PR? We'll see if this works better.

**Comment by huaixv** [comment]
> In this case, why not make some modifications to your PR? We'll see if this works better.

OK

**Comment by huaixv** [comment]
@retrhelo Could you please take a look at the commit e6dab6b?

**Comment by retrhelo** [comment]
> @retrhelo Could you please take a look at the commit [e6dab6b](https://github.com/OSCPU/ysyx-workbench/commit/e6dab6b6289eff173da152c189a7a212f939ef54)?

I pulled down your commits almost at the same you pushed it. But I didn't get the time for evaluation since I'm busy with another task, trying to catch the deadline. I will make my reply as soon as I get rid of my current task, within this week.

**Comment by huaixv** [comment]
Thank you very much.

**Comment by retrhelo** [comment]
Using `git reset` is doing nothing more than simply unstaging everything. Please consider such a situation:

1. Some student, let's call her Alice, adds test1.c and test2.c into the project, and uses `make` to build.
2. After some test, Alice decides that test1.c is ready for commit. However, she believes that there're bugs in test2.c.
3. So Alice stages test1.c using `git add`, leaving test2.c unstaged.
4. Alice modifies test2.c and `make` again.
5. As all files are unstaged, Alice can no longer tell which file is bug-free. She has to test both files again to find it out.

I'm not talking about a dedicated case, but one sounds rather natural. Unstaging everything is no better than committing them all, like the old script does.

Also, this new script is **not solving the problem we argued about previously**. Alice may `git add` some files, then switch to `ysyx-tracer` to checkout if her last `make` leaves a log message. I believe that such actions sound natural and reasonable enough. And by doing so, poor Alice again "loses" (You can find them on `ysyx-tracer`, but they seem perfectly lost on `master` branch. As I mentioned before, restoring them from `ysyx-tracer` leads to unnecessary efforts.) all her staged changes from switching back to `master`...

**Comment by huaixv** [comment]
> 5\. As all files are unstaged, Alice can no longer tell which file is bug-free. She has to test both files again to find it out.

The latest commit isn't intended to solve this problem, the current tracer simply commits all changes, and you can't tell one from the other too.
`git reset` is to prevent so-called potential data loss on work branch when switching to another one.

We can't perfectly preserve the working tree status as far, without modifying Git source code.

**Comment by huaixv** [comment]
> We can't perfectly preserve the working tree status as far, without modifying Git source code.

Okay, this is right if we switch to another branch, but `git worktree` can checkout it in a subdir.

In this way, we must make extra effort to transform `git status` output and copy the working tree manually,
and the script will skip ignored files, so if someone _misconfigured_ `.gitignore` file, some files would be missing in tracer branch.

Also, the script depends on `rsync` to do efficient copying and to create directories, etc..

**Comment by retrhelo** [comment]
The key behind the "data loss", is that `ysyx-tracer`'s commits contain changes that are unstaged on `master`. Thus when switched to `ysyx-tracer`, staged changes are considered "committed", so lost on `master` branch. It seems a dead end to achieve the goal: saving every changes in `ysyx-tracer` meanwhile switching freely between branches.

In my opinion, the only solution is to make empty commits on `ysyx-tracer`. I think a bunch of empty commits are totally enough for tracing and originality proof. But I remember you disagreed with this idea when we discussed it before. Since we can't reach an agreement on it, I'll report to @sashimi-yzh for his opinion.

Beside that, I'm totally okay with your commit's BEHAVIOR, since it's now leaving `master` untouched. However, about the implementation, I still have some advices:

1. The script is getting much complicated, so is the chance for errors to occur. Can you make it simpler, or at least leave some comments? Especially about this line:

```bash
cd .. && git status --untracked-files -z | tr '\000' '\n' | cut -c 1-3 --complement | grep -v '^$(TRACER_BRANCH)/' | rsync -aq --files-from=- ./ $(TRACER_BRANCH)/
```

2. My git encounters an error with `git worktree remove`. The flag `-q` is not supported by mine. Git's version is `2.31.1`.

I think it's **almost ready** for a merge, let's see if @sashimi-yzh accepts your solution.

**Comment by huaixv** [comment]
> 3\. My git encounters an error with `git worktree remove`. The flag `-q` is not supported by mine. Git's version is `2.31.1`.

You are right. `git worktree remove` doesn't take a `-q` option to supress its output, I changed it to `-f` to do force removal.

> `cd .. && git status --untracked-files -z | tr '\000' '\n' | cut -c 1-3 --complement | grep -v '^$(TRACER_BRANCH)/' | rsync -aq --files-from=- ./ $(TRACER_BRANCH)/`

We change dir to `YSYX_HOME`, and use `git status` to get a list of changed files, and use `rsync` to copy them to tracer branch.
But we need to pay attention:
- `git status` list only files not dirs, thus I'd prefer `rsync` to `cp` as it can create directories automatically;
- `git status` will not list untracked files by default, and `--untracked-files` will override this behavior;
- `git status` will quote filenames containing spaces, making `rsync` unhappy, so we use `-z` to override this behavior;
- `-z` option will change the delimiter from `\n` to `NULL`, so we use `tr '\000' '\n'` to revert this change;
- `cut -c 1-3 --complement` will remove status indicator and leave filenames intact;
- `git status` output will also include the newly checked-out worktree, use `grep -v '^$(TRACER_BRANCH)/'` to skip it;

That's how to get a list of files to copy, and we tell `rsync` to read the file list from `stdin` and be quiet then do the copy stuff.

**Comment by retrhelo** [comment]
The reply is here: this PR fits project's need. @sashimi-yzh agrees with your idea. However, there're some advices from him:

1. The script is using relative path like `..`. It may be better to replace them with an absolute path, say `YSYX_HOME`. You may modify `init.sh` to add this change.
2. There should be some comments in the script. Use some comments to describe the behavior of your script.

**Comment by sashimi-yzh** [comment]
Thank you very much for implementing such feature!

**Comment by huaixv** [comment]
> Thank you very much for implementing such feature!

@sashimi-yzh Thank you for thinking of this great idea!

> 2\. There should be some comments in the script. Use some comments to describe the behavior of your script.

Makefile don't allow us to put normal comment in multi-line commands (or pipes).
Here we leverage _command substitution_ from bash to put comments in these quotation blocks,
and it will spawn a few subshells to execute the comments, causing some performance loss.
Also, we need to pay some attention to script syntax (adding semicolons, move these blocks around etc.) to make bash happy.

**Comment by huaixv** [comment]
> When I tried to simulate after a commit, I found that the file change in that commit would not sync to tracer branch. It looks like the sync mechanism is only operative for uncommmited changes.

Yes, we should run `git status` against tracer branch instead  of HEAD.

**Comment by huaixv** [comment]
I found an old [thread](https://lore.kernel.org/git/87wswalkad.fsf@catnip.gol.com/)  in kernel mailing list. 
IIUC, we can manually backup & restore `.git/index` to preserve staging area status, without struggling with git CLI.

**Comment by sashimi-yzh** [comment]
Great! Would you please try such solution?

**Comment by huaixv** [comment]
> Great! Would you please try such solution?

I opened a new PR, see #2.

**Pull request merged**
